name: park_smart
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  flutter_map: ^8.1.1
  geolocator: ^14.0.0
  latlong2: ^0.9.1
  http: ^1.4.0
  google_maps_flutter: ^2.12.2
  permission_handler: ^12.0.0+1
  flutter_polyline_points: ^2.1.0
  cloud_firestore: ^5.6.8
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

